image: golang:1

binaries:
  before_script:
    - mkdir -p /go/src/srv-gitlab.tecnospeed.local/labs/
    - mv ../act /go/src/srv-gitlab.tecnospeed.local/labs/
    - cd /go/src/srv-gitlab.tecnospeed.local/labs/act
    - go get ./...
    - go get github.com/inconshreveable/mousetrap
  script:
    - GOOS=linux GOARCH=amd64 go build -o /builds/labs/act/linux-amd64/act
    - GOOS=darwin GOARCH=amd64 go build -o /builds/labs/act/osx-amd64/act
    - GOOS=windows GOARCH=amd64 go build -o /builds/labs/act/win-amd64/act.exe --ldflags="-H windowsgui"
    - GOOS=windows GOARCH=386 go build -o /builds/labs/act/win-386/act.exe --ldflags="-H windowsgui"
  artifacts:
    paths:
      - /builds/labs/act/linux-amd64/act
      - /builds/labs/act/osx-amd64/act
      - /builds/labs/act/win-amd64/act.exe
      - /builds/labs/act/win-386/act.exe
